services:
  web:
    env_file:
      - path: ./config/config.env
      # dns:
      #   - 10.177.80.130 #example: 8.8.8.8
    build:
      context: ./
      # Correct the path to your Dockerfile
      dockerfile: dockerfile
    # [hostport:containerport] hostport is how the external network connects to your app.
    # container port is for apps inside the container to cnnect to each other.
    ports:
      - 8000:8000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=dev_db
      - MONGO_INITDB_ROOT_USERNAME=sa
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./data/db:/data/db
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
