services:
  web:
    image: golang:1.22.5-alpine
    env_file:
      - path: ./env/web.env
      # dns:
      #   - 10.177.80.130 #example: 8.8.8.8
      # build:
      #   context: ./
      # Correct the path to your Dockerfile
      # dockerfile: dockerfile
      # [hostport:containerport]
    ports:
      - 8000:8000
    # Important to bind/mount your codebase dir to /app dir for live reload
    working_dir: /app
    command: >
      sh -c "go install github.com/air-verse/air@latest && 
             go get go.mongodb.org/mongo-driver/mongo &&
             go get golang.org/x/oauth2 &&
             go get golang.org/x/oauth2/google &&
             air -c .air.toml"
    volumes:
      - ./:/app
    depends_on:
      mongo:
        condition: service_started
  mongo:
    image: mongo
    ports:
      - 27017:27017
    env_file:
      - path: ./env/mongo.env
    volumes:
      - ./data/db:/data/db
      - ./data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
